source 'http://rubygems.org/'

gem 'coffee-script'
gem 'compass'
gem 'guard'
gem 'guard-shell'
gem 'haml'
gem 'rb-inotify'
gem 'kramdown'
gem 'nokogiri'
gem 'sass'
gem 'slop'
gem 'stasis', git: 'git@github.com:budu/stasis.git'
